name: 'Releases'
on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: ยก
          if [[ "${{ github.event.head_commit.message }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-z]+)?$ ]]; then
            git tag "${{ github.event.head_commit.message }}"
            git push --tags
            gh release create
          else
            echo "Muh ist keine versionsnummer"
          fi
