name: Publish Release to npm
on:
  release:
    types: [published]
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # 4.0.3
        with:
          node-version: "22"
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test
      - if: ${{ github.event.release.tag_name != '' && env.NPM_PUBLISH_TAG != '' }}
        run: npm publish --provenance --access=public --tag=${{ env.NPM_PUBLISH_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PUBLISH_TAG: ${{ contains(github.event.release.tag_name, '-beta.') && 'beta' || contains(github.event.release.tag_name, '-alpha.') && 'canary' || 'latest' }}
